# Autograd: Automatic Differentiation
Central to all neural networks in PyTorch is the autograd package. Let’s first briefly visit this, and we will then go to training our first neural network.

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

In [1]:
import torch

Create a tensor and set requires_grad=True to track computation with it. By default when we initialize a tensor, the requires_grad attribute is set to False.

In [3]:
x = torch.ones(2, 2)
print(x)
print(x.requires_grad)

tensor([[1., 1.],
        [1., 1.]])
False


In [14]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Let's do a tensor operation

In [15]:
y = x + 2
print(y)

# Do more operations on y
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


We created a small computational graph above. Let's backprop to compute the derivatives.

In [16]:
print(x.grad)
out.backward()       # grad can be implicitly created only for scalar outputs
print(x.grad)        # d(out)/dx

None
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
